name: adventofcode2019
description: My solutions for the advent of code 2019

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  sprintf: ^4.0.2
  trotter: ^1.0.2
  quiver: ^2.1.2+1
  console: ^3.1.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
